In [1]:
import mysql.connector

dataBase = mysql.connector.connect(
    host = "localhost",
    user ="root",
    passwd = ""
)

cursorObject = dataBase.cursor()

cursorObject.execute("CREATE DATABASE db_sales_V3922012")
print("Database berhasil dibuat")

Database berhasil dibuat

In [2]:
# menghubungkan dan mengoperasikan database MySQL dari Python.
import mysql.connector

#Buat koneksi ke database MySQL menggunakan metode mysql.connector.connect(), koneksi ke database d3_ti_2023 pada server localhost dilakukan dengan username root dan tanpa password.
conn = mysql.connector.connect(user = 'root',
    host = 'localhost',
    database = 'db_sales_V3922012')

#Cetak koneksi untuk mengecek apakah koneksi berhasil terbentuk.
print(conn)

#Tutup koneksi ke database MySQL 
conn.close

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000189900A7CD0>

In [3]:
# menghubungkan dan mengoperasikan database MySQL dari Python
import mysql.connector

#buat koneksi ke database MySQL
dataBase = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="",
    database="db_sales_V3922012"
)

cursorObject = dataBase.cursor() #mengeksekusi perintah SQL dan mengambil hasilnya

cursorObject.execute("use db_sales_V3922012") #memilih database agar program dapat dijalankan

# membuat Tabel Mata Kuliah
#yang terdiri dari kolom kode mata kuliah, nama, waktu, dan ruangan 
matkulTable = """CREATE TABLE DATA_STOK_BARANG (
                 id_barang VARCHAR(255) PRIMARY KEY,
                 nama_barang VARCHAR(255),
                 harga_barang INT,
                 stok_awal INT,
                 barang_masuk INT,
                 barang_keluar INT,
                 stok_akhir INT
                 )"""

cursorObject.execute(matkulTable) #menjalankan perintah SQL untuk membuat tabel MATA_KULIAH
print("Tabel Data Stok Barang berhasil dibuat")#print pesan berhasil

Tabel Data Stok Barang berhasil dibuat

In [4]:
import mysql.connector

# Koneksi ke database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="db_sales_V3922012"
)

# Fungsi untuk memasukkan data
def insert_data():
    id_barang = input("Masukkan ID Barang: ")
    nama_barang = input("Masukkan Nama Barang: ")
    harga_barang = int(input("Masukkan Harga Barang: "))
    stok_awal = int(input("Masukkan Stok Awal: "))
    barang_masuk = int(input("Masukkan Barang Masuk: "))
    barang_keluar = int(input("Masukkan Barang Keluar: "))
    stok_akhir = stok_awal + barang_masuk - barang_keluar

    # Membuat objek cursor
    cursor = mydb.cursor()

    # Query untuk memasukkan data ke dalam tabel
    query = f"INSERT INTO DATA_STOK_BARANG (id_barang, nama_barang, harga_barang, stok_awal, barang_masuk, barang_keluar, stok_akhir) " \
        f"VALUES ('{id_barang}', '{nama_barang}', {harga_barang}, {stok_awal}, {barang_masuk}, {barang_keluar}, {stok_akhir})"

    # Eksekusi query
    cursor.execute(query)

    # Commit perubahan ke database
    mydb.commit()

    print(cursor.rowcount, "data berhasil ditambahkan.")

In [5]:
import mysql.connector

# Koneksi ke database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="db_sales_V3922012"
)

# Fungsi untuk menampilkan data
def show_data():
    # Membuat objek cursor
    cursor = mydb.cursor()

    # Query untuk mengambil data dari tabel
    query = "SELECT * FROM DATA_STOK_BARANG"

    # Eksekusi query
    cursor.execute(query)

    # Menampilkan data
    result = cursor.fetchall()
    for row in result:
        Id_barang = row[0]
        Nama_Barang = row[1]
        Harga_Barang = row[2]
        Stok_Awal = row[3]
        Barang_Masuk = row[4]
        Barang_keluar = row[5]
        Stok_Akhir = row[6]
        print("Id barang : ", Id_barang)
        print("Nama barang : ", Nama_Barang)
        print("Harga barang : ", Harga_Barang)
        print("Stok awal : ", Stok_Awal)
        print("Barang masuk : ", Barang_Masuk)
        print("Barang keluar : ", Barang_keluar)
        print("Stok akhir : ", Stok_Akhir)

In [7]:
import mysql.connector

# Koneksi ke database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="db_sales_V3922012"
)

# Fungsi untuk memperbarui data
def update_data():
    # Membuat objek cursor
    cursor = mydb.cursor()

    # Menampilkan data terlebih dahulu untuk memilih data yang akan diubah
    show_data()

    # Meminta pengguna untuk memasukkan ID barang yang akan diubah
    id_barang = input("Masukkan ID Barang yang akan diubah: ")

    # Meminta pengguna untuk memasukkan nilai baru untuk setiap kolom
    new_nama_barang = input("Masukkan Nama Barang baru: ")
    new_harga_barang = input("Masukkan Harga Barang baru: ")
    new_stok_awal = input("Masukkan Stok Awal baru: ")
    new_barang_masuk = input("Masukkan Barang Masuk baru: ")
    new_barang_keluar = input("Masukkan Barang Keluar baru: ")
    new_stok_akhir = input("Masukkan Stok Akhir baru: ")

    # Query untuk memperbarui data pada tabel
    query = "UPDATE barang SET `Nama Barang` = %s, `Harga Barang` = %s, `Stok Awal` = %s, `Barang Masuk` = %s, `Barang Keluar` = %s, `Stok Akhir` = %s WHERE `Id Barang` = %s"
    values = (new_nama_barang, new_harga_barang, new_stok_awal, new_barang_masuk, new_barang_keluar, new_stok_akhir, id_barang)

    # Eksekusi query
    cursor.execute(query, values)

    # Commit perubahan ke database
    mydb.commit()

    # Menampilkan pesan sukses
    print(cursor.rowcount, "data berhasil diubah.")

In [8]:
import mysql.connector

# Koneksi ke database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="db_sales_V3922012"
)

# Fungsi untuk menghapus data
def delete_data():
    # Membuat objek cursor
    cursor = mydb.cursor()

    # Menampilkan data terlebih dahulu untuk memilih data yang akan dihapus
    show_data()

    # Meminta pengguna untuk memasukkan ID barang yang akan dihapus
    id_barang = input("Masukkan ID Barang yang akan dihapus: ")

    # Query untuk menghapus data pada tabel
    query = "DELETE FROM DATA_STOK_BARANG WHERE `Id Barang` = %s"
    value = (id_barang,)

    # Eksekusi query
    cursor.execute(query, value)

    # Commit perubahan ke database
    mydb.commit()

    # Menampilkan pesan sukses
    print(cursor.rowcount, "data berhasil dihapus.")

In [ ]:
import mysql.connector

# Koneksi ke database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="db_sales_V3922012"
)

# Fungsi untuk mencari data berdasarkan ID
def find_data_by_id(id_barang):
    # Membuat objek cursor
    cursor = mydb.cursor()

    # Query untuk mencari data pada tabel
    query = "SELECT * FROM nama_tabel WHERE id_barang = %s"
    values = (id_barang,)

    # Eksekusi query
    cursor.execute(query, values)

    # Menampilkan data
    data = cursor.fetchone()
    if data:
        print("ID Barang :", data[0])
        print("Nama Barang :", data[1])
        print("Harga Barang :", data[2])
        print("Stok Awal :", data[3])
        print("Barang Masuk :", data[4])
        print("Barang Keluar :", data[5])
        print("Stok Akhir :", data[6])
    else:
        print("Data tidak ditemukan")

# Panggil fungsi find_data_by_id
find_data_by_id(1)

In [ ]:
while True:
    print("APLIKASI DATA BASE PYTHON")
    print("1. insert data")
    print("2. tampilkan data")
    print("3. update data")
    print("4. hapus data")
    print("5. cari data")
    print("0. keluar")
    
    # Meminta input dari user
    pilihan = input("Masukkan pilihan Anda: ")

    # Menjalankan fungsi sesuai dengan pilihan user
    if pilihan == "1":
        insert_data()
    elif pilihan == "2":
        show_data()
    elif pilihan == "3":
        update_data()
    elif pilihan == "4":
        delete_data()
    elif pilihan == "5":
        search_data()
    elif pilihan == "0":
        print("Terima kasih sudah menggunakan aplikasi ini")
        break
    else:
        print("Pilihan tidak valid. Silahkan masukkan pilihan yang sesuai.")